FORMAT: 1A
HOST: http://www.somi-d8.loc/

# SmartOffice

SmartOffice API to interact with embedded devices.

## Access Request [/api/v1/node/access]

### Request Access By UID For Node [GET]

Embedded lock device may request access on pcd trigger. 
UID, pcd_number and time should be returned same as the came, because of they used to invalidate events device-side.

+ Request (application/json)

    + Headers

            destination: %bo_name%
            action: access request
            node-id: %id%
            time: %time%
            uid: %uid%
            pcd-number: %pcd_number%

+ Response 200 (application/json)

    + Headers 

            destination: %id%
            action: access request
            node-id: %bo_name%
            time: %time%
            uid: %uid%
            pcd-number: %pcd_number%
            access: %acess_result%

+ Response 403 (application/json)

    + Headers 

    + Body

            {
                "error": {
                "message": "User is not authorized.",
                "code": 0
                }
            }

## Time Synchronization [/api/v1/node/time-sync]

### Time Synchronization For Node [POST]

Node (PCD) issues request to sync local ticks with server's timestamp.

+ Request (application/json)

    + Headers

            destination: %bo_name%
            action: time-sync
            node-id: %id%
            time: %time%


+ Response 200 (application/json)

    + Headers

            destination: %id%
            action: time sync
            node-id: %bo_name%
            time: %time%

+ Response 403 (application/json)

    + Headers 

    + Body

            {
                "error": {
                "message": "User is not authorized.",
                "code": 0
                }
            }

## Event Synchronization [/api/v1/node/event]

### Node Events Synchronization. It's cache related logic. [POST]

Embedded lock device caches events (usecase - avoid stuck in case of server/network problems).
This request should sync events, and clear synced ones from embedded device build-in cache.
UID, pcd_number and time should be returned same as the came, because of they used to invalidate device-side events.

+ Request (application/json)

    + Headers

            destination: %bo_name%
            action: event dump
            node-id: %id%
            time: %time%
            uid: %uid%
            pcd-number: %pcd_number%
            access: %access%
            cached: %cached%

+ Response 200 (application/json)

    + Headers 

            destination: %id%
            action: event dump
            node-id: %bo_name%
            time: %time%
            uid: %uid%
            pcd-number: %pcd_number%

+ Response 403 (application/json)

    + Headers 

    + Body

            {
                "error": {
                "message": "User is not authorized.",
                "code": 0
                }
            }