FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# SmartOffice

SmartOffice API to interact with embedded devices.

## Access Request [/api/v1/node/access]

### Request Access By UID For Node [GET]

+ Request (application/json)

    + Headers

            destination: %bo_name%
            action: access request
            node_id: %id%
            time: %time%
            uid: %uid%
            pcd_number: %pcd_number%

+ Response 200 (application/json)

    + Headers 

            destination: %id%
            action: access request
            node_id: %bo_name%
            time: %time%
            uid: %uid%
            pcd_number: %pcd_number%
            access: %acess_result%

+ Response 403 (application/json)

    + Headers 

    + Body

            {
                "error": {
                "message": "User is not authorized.",
                "code": 0
                }
            }

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
