FORMAT: 1A
HOST: http://www.somi-d8.loc/

# SmartOffice

SmartOffice API to interact with embedded devices.

## Access Request [/api/v1/node/access]

### Request Access By UID For Node [GET]

Embedded lock device may request access on pcd trigger. 
UID, pcd_number and time should be returned same as the came, because of they used to invalidate events device-side.

+ Request (application/json)

    + Headers

            destination: %bo_name%
            action: access request
            node-id: %id%
            time: %time%
            uid: %uid%
            pcd-number: %pcd_number%

+ Response 200 (application/json)

    + Headers 

            destination: %id%
            action: access request
            node-id: %bo_name%
            time: %time%
            uid: %uid%
            pcd-number: %pcd_number%
            access: %acess_result%

+ Response 403 (application/json)

    + Headers 

    + Body

            {
                "error": {
                "message": "User is not authorized.",
                "code": 0
                }
            }

## Time Synchronizing [/api/v1/node/time-sync]

### Time Synchronizing For Node [POST]

Request called from device to sync local RTC with server.

+ Request (application/json)

    + Headers

            destination: %bo_name%
            action: time-sync
            node-id: %id%
            time: %time%


+ Response 200 (application/json)

    + Headers

            destination: %id%
            action: time sync
            node-id: %bo_name%
            time: %time%

+ Response 403 (application/json)

    + Headers 

    + Body

            {
                "error": {
                "message": "User is not authorized.",
                "code": 0
                }
            }